# shellcheck shell=bash

cmd_exec_opencode() {
  ensure_dirs
  local galley_raw="${1:-}"
  shift || true
  if [ -z "$galley_raw" ]; then
    fail "Usage: cli/linotype exec brief <galley-name> [--copy] [--by-domain]"
    exit 1
  fi

  local copy=0 by_domain=0
  while [ $# -gt 0 ]; do
    case "${1:-}" in
      --copy) copy=1; shift ;;
      --by-domain) by_domain=1; shift ;;
      *) break ;;
    esac
  done

  local galley; galley="$(kebab_case "$galley_raw")"
  local gdir; gdir="$(find_galley_dir "$galley" || true)"
  if [ -z "${gdir:-}" ]; then fail "Galley not found: $galley"; exit 1; fi

  local stage; stage="$(galley_stage_of_dir "$gdir")"
  if [ "$stage" != "queue" ]; then
    warn "Galley is in $stage (preferred: queue). Proceeding."
  fi

  local run_sheet="$gdir/run-sheet.md"
  if [ ! -f "$run_sheet" ]; then
    warn "Missing run-sheet.md in ${gdir#"$ROOT_DIR/"}. Executor brief will be generated from slugs only."
  fi

  shopt -s nullglob
  local slugs=()
  local s
  for s in "$gdir"/slugs/*.md; do
    [ -f "$s" ] || continue
    [ "$(basename "$s")" = "README.md" ] && continue
    slugs+=("$s")
  done
  shopt -u nullglob

  if [ "${#slugs[@]}" -eq 0 ]; then
    warn "No slugs found under ${gdir#"$ROOT_DIR/"}/slugs/"
  fi

  if [ "$by_domain" -eq 1 ]; then
    _exec_brief_by_domain "$galley" "$gdir" "$stage" "$run_sheet" "${slugs[@]}"
    return 0
  fi

  local brief
  brief="$(_exec_build_brief "$galley" "$gdir" "$stage" "$run_sheet" "${slugs[@]}")"

  if [ "$copy" -eq 1 ]; then
    if command -v pbcopy >/dev/null 2>&1; then
      printf "%s" "$brief" | pbcopy
      ok "Copied executor brief to clipboard (pbcopy)"
      return 0
    fi
    if command -v xclip >/dev/null 2>&1; then
      printf "%s" "$brief" | xclip -selection clipboard
      ok "Copied executor brief to clipboard (xclip)"
      return 0
    fi
    warn "No clipboard tool found (pbcopy/xclip). Printing to stdout instead."
  fi

  printf "%s\n" "$brief"
}

_exec_build_brief() {
  local galley="$1" gdir="$2" stage="$3" run_sheet="$4"
  shift 4
  local slugs=("$@")

  {
    echo "# Executor brief (generated by linotype)"
    echo
    echo "Galley: $galley"
    echo "Stage: $stage"
    echo "Galley dir: ${gdir#"$ROOT_DIR/"}"
    echo
    echo "## Execution contract"
    echo "- Execute slugs in order without waiting for confirmation."
    echo "- Stop only when:"
    echo "  - blocked by ambiguity that changes behaviour"
    echo "  - acceptance checks fail and cannot be fixed safely"
    echo "  - a decision marked gated is reached"
    echo "- If not blocked: make the safest minimal assumption and record an open question in review.md or the slug."
    echo
    echo "## Branch, isolation, commits"
    echo "- One branch per galley; prefer a dedicated worktree."
    echo "- Commit after each slug:"
    echo "  - slug: slug:<slug-name> done - <summary> #galley:$galley"
    echo "  - galley: galley:$galley ready for review - <summary>"
    echo

    if [ -f "$run_sheet" ]; then
      echo "## Run Sheet"
      echo
      cat "$run_sheet"
      echo
    fi

    echo "## Slugs (in filesystem order)"
    echo
    local i=1 f base autonomy purpose
    for f in "${slugs[@]}"; do
      base="$(basename "$f")"
      autonomy="$(slug_header_field "$f" "autonomy" | head -n1)"
      purpose="$(slug_header_field "$f" "purpose" | head -n1)"
      [ -z "$autonomy" ] && autonomy="continuous"
      echo "${i}. ${base} (autonomy: ${autonomy})"
      if [ -n "$purpose" ]; then
        echo "   - purpose: $purpose"
      fi
      echo "   - file: ${f#"$ROOT_DIR/"}"
      i=$((i + 1))
    done
    echo
    echo "## Notes for the executor tool"
    echo "- Work within allowed paths and the active galley scope."
    echo "- Do not refactor unrelated code."
  } | cat
}

_exec_brief_by_domain() {
  local galley="$1" gdir="$2" stage="$3" run_sheet="$4"
  shift 4
  local slugs=("$@")

  # Group slugs by domain (from slug header; fallback: core)
  declare -A domain_slugs
  local f domain
  for f in "${slugs[@]}"; do
    domain="$(slug_header_field "$f" "domain" | head -n1 | tr -d '[:space:]')"
    [ -z "$domain" ] && domain="core"
    domain_slugs[$domain]+="${domain_slugs[$domain]:+ }$f"
  done

  local d
  for d in $(printf '%s\n' "${!domain_slugs[@]}" | sort); do
    echo "---"
    echo "# Executor brief: domain=$d (for subagent)"
    echo
    local domain_slug_list=()
    for f in ${domain_slugs[$d]}; do domain_slug_list+=("$f"); done
    _exec_build_brief "$galley" "$gdir" "$stage" "$run_sheet" "${domain_slug_list[@]}"
    echo
    echo "## Allowed paths (domain $d)"
    echo "- src/${d}/, docs/domain/${d}.md, and paths from run-sheet Constraints"
    echo "- Work only in these paths. Update Domain updates when done."
    echo
  done
}
