# shellcheck shell=bash

cmd_exec_opencode() {
  ensure_dirs
  local galley_raw="${1:-}"
  shift || true
  if [ -z "$galley_raw" ]; then
    fail "Usage: cli/linotype exec brief <galley-name> [--copy]"
    exit 1
  fi

  local copy=0
  while [ $# -gt 0 ]; do
    case "${1:-}" in
      --copy) copy=1; shift ;;
      *) break ;;
    esac
  done

  local galley; galley="$(kebab_case "$galley_raw")"
  local gdir; gdir="$(find_galley_dir "$galley" || true)"
  if [ -z "${gdir:-}" ]; then fail "Galley not found: $galley"; exit 1; fi

  local stage; stage="$(galley_stage_of_dir "$gdir")"
  if [ "$stage" != "queue" ]; then
    warn "Galley is in $stage (preferred: queue). Proceeding."
  fi

  local run_sheet="$gdir/run-sheet.md"
  if [ ! -f "$run_sheet" ]; then
    warn "Missing run-sheet.md in ${gdir#"$ROOT_DIR/"}. Executor brief will be generated from slugs only."
  fi

  shopt -s nullglob
  local slugs=()
  local s
  for s in "$gdir"/slugs/*.md; do
    [ -f "$s" ] || continue
    [ "$(basename "$s")" = "README.md" ] && continue
    slugs+=("$s")
  done
  shopt -u nullglob

  if [ "${#slugs[@]}" -eq 0 ]; then
    warn "No slugs found under ${gdir#"$ROOT_DIR/"}/slugs/"
  fi

  local brief
  brief="$(
    {
      echo "# Executor brief (generated by linotype)"
      echo
      echo "Galley: $galley"
      echo "Stage: $stage"
      echo "Galley dir: ${gdir#"$ROOT_DIR/"}"
      echo
      echo "## Execution contract"
      echo "- Execute slugs in order without waiting for confirmation."
      echo "- Stop only when:"
      echo "  - blocked by ambiguity that changes behaviour"
      echo "  - acceptance checks fail and cannot be fixed safely"
      echo "  - a decision marked gated is reached"
      echo "- If not blocked: make the safest minimal assumption and record an open question in review.md or the slug."
      echo
      echo "## Branch, isolation, commits"
      echo "- One branch per galley; prefer a dedicated worktree."
      echo "- Commit after each slug:"
      echo "  - slug: slug:<slug-name> done - <summary> #galley:$galley"
      echo "  - galley: galley:$galley ready for review - <summary>"
      echo

      if [ -f "$run_sheet" ]; then
        echo "## Run Sheet"
        echo
        cat "$run_sheet"
        echo
      fi

      echo "## Slugs (in filesystem order)"
      echo
      local i=1
      local f
      for f in "${slugs[@]}"; do
        local base; base="$(basename "$f")"
        local autonomy; autonomy="$(slug_header_field "$f" "autonomy" | head -n1)"
        local purpose; purpose="$(slug_header_field "$f" "purpose" | head -n1)"
        [ -z "$autonomy" ] && autonomy="continuous"
        echo "${i}. ${base} (autonomy: ${autonomy})"
        if [ -n "$purpose" ]; then
          echo "   - purpose: $purpose"
        fi
        echo "   - file: ${f#"$ROOT_DIR/"}"
        i=$((i + 1))
      done
      echo
      echo "## Notes for the executor tool"
      echo "- Work within allowed paths and the active galley scope."
      echo "- Do not refactor unrelated code."
    } | cat
  )"

  if [ "$copy" -eq 1 ]; then
    if command -v pbcopy >/dev/null 2>&1; then
      printf "%s" "$brief" | pbcopy
      ok "Copied executor brief to clipboard (pbcopy)"
      return 0
    fi
    if command -v xclip >/dev/null 2>&1; then
      printf "%s" "$brief" | xclip -selection clipboard
      ok "Copied executor brief to clipboard (xclip)"
      return 0
    fi
    warn "No clipboard tool found (pbcopy/xclip). Printing to stdout instead."
  fi

  printf "%s\n" "$brief"
}
